<a href="https://colab.research.google.com/github/hindia-vic/reinforcement_learning/blob/main/frozenlake_reinforcement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import  gym
import random
import time
from IPython.display import clear_output

In [15]:
print(gym.__version__)

0.25.2


In [25]:
env=gym.make("FrozenLake-v1",new_step_api=True)

In [26]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n
q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
num_episodes=10000
max_steps_per_episode=250
learning_rate=0.1
discount_rate=0.99
exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.001

In [32]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        # Handle the case where more than 4 values are returned
        result = env.step(action)
        new_state, reward, done = result[:3]
        # If there are more values, they will be ignored

        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
                                 learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward

        if done:
            break

    exploration_rate = min_exploration_rate + \
                       (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes // 1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r) / 1000))
    count += 1000

********Average reward per thousand episodes********

1000 : 0.054
2000 : 0.2
3000 : 0.404
4000 : 0.592
5000 : 0.685
6000 : 0.751
7000 : 0.734
8000 : 0.756
9000 : 0.751
10000 : 0.77


In [30]:
print(q_table)

[[0.5585581  0.4850327  0.5039981  0.50043675]
 [0.38585999 0.32309012 0.27270079 0.46201438]
 [0.33821819 0.26944653 0.26907631 0.26461387]
 [0.13762215 0.01976431 0.0553618  0.0188478 ]
 [0.5727923  0.39130629 0.38856612 0.44663084]
 [0.         0.         0.         0.        ]
 [0.22445042 0.13133267 0.15133533 0.09581136]
 [0.         0.         0.         0.        ]
 [0.46453026 0.35364037 0.33725339 0.5970324 ]
 [0.38066087 0.62784076 0.45377206 0.43062999]
 [0.52748738 0.35508155 0.4207657  0.23661497]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.36452103 0.44409536 0.77680078 0.35619656]
 [0.70079942 0.90494425 0.78959465 0.73080054]
 [0.         0.         0.         0.        ]]
